[openai]
api_key = "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"

[db]
DB_HOST = "sql3.freesqldatabase.com"
DB_USER = "sql3817481"
DB_PASSWORD = "398j6uKWle"
DB_NAME = "sql3817481"
DB_PORT = 3306